# This is an Extension: https://github.com/compose-spec/compose-spec/blob/main/spec.md#extension
x-environment: &env
  env_file:
    - ./.env

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    entrypoint: ./docker/web/start_server.sh
    restart: always
    volumes:
      - ./:/app # Mount the current directory to /app within the container (for dev)
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://127.0.0.1:8000/healthcheck/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    <<: *env # This is a YAML merge

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    restart: always
    volumes:
      - ./:/app
    depends_on:
      django:
        # Migrations need to be run before celery can start because of django-celery-results
        condition: service_healthy
    <<: *env

  redis:
    container_name: redis
    image: redis:alpine
    restart: always

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    volumes:
      - db-vol:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
    <<: *env

volumes:
  db-vol:
