# This is an Extension: https://github.com/compose-spec/compose-spec/blob/main/spec.md#extension
x-environment: &env
  env_file:
    - ./.env

services:
  django:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    entrypoint: ./docker/web/start_server.sh
    volumes:
      - ./:/app # Mount the current directory to /app within the container
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    <<: *env # This is a YAML merge

  celery:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - django # Migrations need to be run before celery can start because of django-celery-results
    <<: *env

  redis:
    image: redis:alpine

  postgres:
    image: postgres:alpine
    volumes:
      - db-vol:/var/lib/postgresql/data
    <<: *env

volumes:
  db-vol:
