# Generated by Django 5.0.1 on 2024-02-01 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_collection_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.TextField(choices=[('present', 'Present'), ('bunked', 'Bunked'), ('cancelled', 'Cancelled')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
