# Generated by Django 5.0.1 on 2024-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_collection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='threshold',
            field=models.IntegerField(default=75),
        ),
    ]
