# Generated by Django 5.0.1 on 2024-02-03 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_collection_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 4, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 2, 2)),
            preserve_default=False,
        ),
    ]
