# Generated by Django 5.0.1 on 2024-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_collection_end_date_collection_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
