name: Deploy the backend

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Update homeserver and restart it
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd src/Backend
          git fetch origin 
          git reset --hard origin/main
          sudo systemctl restart webserver.service
