name: Deploy the backend to the homeserver


on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
     - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Update homeserver and restart it
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd src/Backend
          git fetch origin homeserver
          git reset --hard origin/homeserver
          sudo systemctl restart webserver.service
